service: ff-draft-dashboard-api

custom:
  secrets: ${file(config.prod.yml)}

frameworkVersion: "2"

provider:
  name: aws
  runtime: go1.x
  stage: ${self:custom.secrets.ENV}
  versionFunctions: false # dont store versions of all funcs

plugins:
  - serverless-go-build
package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  get-harris-ranks:
    handler: entrypoints/get-harris-ranks/main.go
    environment:
      ALLOWED_ORIGIN: ${self:custom.secrets.ALLOWED_ORIGIN}
    events:
      - http:
          path: harris-ranks
          method: get
          cors:
            origin: ${self:custom.secrets.ALLOWED_ORIGIN}
            allowCredentials: "true"

  # get-fpros-ranks:
  #   handler: entrypoints/get-fpros-ranks/main.go
  #   environment:
  #     ALLOWED_ORIGIN: ${self:custom.secrets.ALLOWED_ORIGIN}
  #   events:
  #     - http:
  #         path: fpros-ranks
  #         method: get
  #         cors:
  #           origin: ${self:custom.secrets.ALLOWED_ORIGIN}
  #           allowCredentials: "true"
